/*
 Navicat Premium Data Transfer

 Source Server         : local
 Source Server Type    : MySQL
 Source Server Version : 100417
 Source Host           : localhost:3306
 Source Schema         : sendasur_socios

 Target Server Type    : MySQL
 Target Server Version : 100417
 File Encoding         : 65001

 Date: 07/05/2021 18:47:20
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ecoturism_centers
-- ----------------------------
DROP TABLE IF EXISTS `ecoturism_centers`;
CREATE TABLE `ecoturism_centers`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description_large` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ubication` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `services` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `activities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `is_active` tinyint(4) NULL DEFAULT 1,
  `type` enum('socio','colaborador') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `ecoturism_centers_slug_unique`(`slug`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 24 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of ecoturism_centers
-- ----------------------------
INSERT INTO `ecoturism_centers` VALUES (1, 'Campamento Poza Po\'op Chan', 'campamento-poza-poop-chan', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654792/socios/CAMPAMENTO%20POSA%20PO%C2%B4OP%20CHAN-20210403T064318Z-001/CAMPAMENTO%20POSA%20PO%C2%B4OP%20CHAN/ZA_SAK_TZ_I-PLAN_DE_AYUTLA1_hherut.jpg', 'Es un grupo de trabajo integrado por 6 familias de origen Tzeltal  en la comunidad de Nueva Palestina, donde su actividad principal es la agricultura.', 'Es un grupo de trabajo integrado por 6 familias de origen Tzeltal  en la comunidad de Nueva Palestina, donde su actividad principal es la agricultura. Comenzaron poco a poco a valorar sus riquezas naturales y a darse cuenta de la necesidad urgente de protegerlas y conservarlas, es así como surge el Centro Ecoturístico, como una de las alternativas para lograrlo y generar ingresos económicos para sus familias.\r\nEl complejo turístico de Poza Po´op chan conjunta una serie de atractivos de gran potencial para la práctica de actividades de aventura. En compañía de guías locales, visita la cascada de las Golondrinas y nadar en las pozas naturales si así lo prefieres. Descansa en cabañas económicas con baño o acampa a orillas del río y disfruta de una fogata al caer la noche. En las puertas de la Selva Lacandona, Nueva Palestina es el principio de la aventura verde.', 'Palestina se ubica en la región VI selva, en la  selva Lacandona, a 107 kilómetros de Palenque sobre la carretera fronteriza del sur, se toma un desvío de 12 kilómetros a Nueva Palestina hasta acceder a poza Po\'op Chan.', NULL, NULL, 1, 'socio', '2021-05-05 16:42:21', '2021-05-05 16:42:21');
INSERT INTO `ecoturism_centers` VALUES (2, 'Centro ecoturístico centro jaguar', 'centro-ecoturistico-centro-jaguar', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654799/socios/CENTRO%20ECOTURISTICO%20ESCUDO%20JAGUAR-20210403T064537Z-001/CENTRO%20ECOTURISTICO%20ESCUDO%20JAGUAR/ZA_YAXCHILAN_1_ij15vw.jpg', 'A orilla del río Usumacinta, bordeado de vegetación tropical, se encuentra el Centro Turístico Escudo Jaguar,  puerta de entrada a las antiguas ciudades mayas ocultas en la exuberante selva de la zona.', 'A orilla del río Usumacinta, bordeado de vegetación tropical, se encuentra el Centro Turístico Escudo Jaguar,  puerta de entrada a las antiguas ciudades mayas ocultas en la exuberante selva de la zona. A dos horas y media de la ciudad de Palenque, Escudo jaguar formado por familias del grupo lingüístico Chol, ofrece al visitante servicios de hospedaje en habitaciones privadas y habitaciones rústicas, área para acampar, restaurant con vista al río,  teléfono e internet satelital en el restaurante y estacionamiento.  Además proponer servicios de lancha para llegar a la zona arqueológica Yaxchilan, a Bethel y Piedras Negras en Guatemala.', 'Frontera Corozal se ubica en la región VI selva,  al margen izquierda del río Usumacinta, en la frontera con Guatemala, a 187 kms de la ciudad de Palenque y se llega a ella por  vía terrestre a través de la carretera fronteriza del sur, hasta el crucero corozal. A partir de aquí se transita por un desvío de 15 kms.', NULL, NULL, 1, 'socio', '2021-05-05 16:46:54', '2021-05-05 16:46:54');
INSERT INTO `ecoturism_centers` VALUES (3, 'Centro ecoturístico las guacamayas', 'centro-ecoturistico-las-guacamayas', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654801/socios/LAS%20GUACAMAYAS-20210403T064603Z-001/LAS%20GUACAMAYAS/RECORRIDO_EN_LANCHA_kpspct.jpg', 'El Centro Ecoturístico las Guacamayas, fue creado con la finalidad de desarrollar un proyecto de conservación de las guacamayas rojas, especies amenazadas por la cacería y al comercio ilegal debido a su colorido y exótico plumaje.', 'El Centro Ecoturístico las Guacamayas, fue creado con la finalidad de desarrollar un proyecto de conservación de las guacamayas rojas, especies amenazadas por la cacería y al comercio ilegal debido a su colorido y exótico plumaje. Aquí también encuentran refugio otras especies de fauna como el tucán, mono saraguato, tejón y armadillo, entre muchos más, en las más de 1,463 hectáreas de superficie de esta reserva ecológica ejidal. Es ideal para los amantes de la naturaleza ya que se puede practicar la observación de aves en su estado silvestre, realizar caminatas por los senderos dominados por la verde plancha de la selva y el sendero de los monos saraguatos (que avisan con sus gritos la entrada de los extraños a su  territorio). Servicios guiados a los dormitorios y área de alimentación y anidación de la guacamaya roja, por área de pastizales y dentro de la comunidad de origen chinanteca, realiza actividades de cayak y paseos en lancha  por los ríos Lacantún y Tzendales.  \r\n\r\nCuenta con cabañas de primer nivel y cabañas rústicas con baño común, servicio de restaurante, internet satelital en el lobby y estacionamiento. Las cabañas están distribuidas de la mejor manera para disfrutar de una estancia mágica, rodeada de vegetación, áreas verdes y andadores ecológicos, cuenta también con un aviario de guacamayas rojas y un venadario. El río Lacantún y la biosfera de Montes Azules son escenario ideal para sentir a la naturaleza en todo su esplendor. \r\n\r\nDesde el año 2008 el centro ecoturístico está certificado de la norma mexicana NMX-AA-133-SCFI-2006 de sustentabilidad del ecoturismo concedida por la Secretaría de Medio Ambiente y Recursos Naturales de México (Semarnat). Este certificado viene como reconocimiento de sus esfuerzos para mejorar la calidad de sus servicios dentro del Centros Ecoturísticos y de sus actitudes amigables con el medioambiente.', 'Se ubica en la región VI selva. Se llega por la carretera fronteriza desde Comitán o Palenque. De Comitán se toma la carretera fronteriza del sur, son 216 kilómetros. Al entronque encontramos Boca del Chajul y ahí son 32 kilómetros. De Palenque se llega por la carretera fronteriza del sur, hasta el kilómetro 194, enseguida se encuentra el desvío o entronque a Zamora Pico de Oro de 25 kilómetros. Posteriormente está el entronque a las Guacamayas a 15 kilómetros.', NULL, NULL, 1, 'socio', '2021-05-05 16:50:57', '2021-05-05 16:50:57');
INSERT INTO `ecoturism_centers` VALUES (4, 'Cooperativa cascada velo de novia - El chiflón', 'cooperativa-cascada-velo-de-novia-el-chiflon', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654803/socios/VELO%20DE%20NOVIA%20EL%20CHIFLON-20210403T065550Z-001/VELO%20DE%20NOVIA%20EL%20CHIFLON/IMG_0684_aenzr8.jpg', 'Se encuentra ubicado en el municipio de Tzimol al margen del río San Vicente. Las cascadas de Chiflón son una serie de caídas de agua de asombrosa belleza que contrasta con la vegetación de la selva baja de esta región subtropical.', 'Se encuentra ubicado en el municipio de Tzimol al margen del río San Vicente. Las cascadas de Chiflón son una serie de caídas de agua de asombrosa belleza que contrasta con la vegetación de la selva baja de esta región subtropical. 1,28 km de caminata en andadores, escaleras y senderos creados por las manos de la gente campesina del lugar para poder apreciar la caída de 120 m de altura de la cascada mayor Velo de Novia.\r\nSobre este mismo sendero el ambiente natural ofrece dos cascadas más de menor tamaño, con diferentes espacios para la práctica de natación. Existe otro sendero diferente que conduce a un área con vestigios arqueológicos, además de que en el sitio existen pinturas rupestres. Cuentan con servicios de hospedaje en cabañas privadas y rusticas, restaurante, ventas de artesanías y recuerdo, una estación de juegos para niños y, para las fanáticos de aventura, una tirolesa que cruza frente a la cascada de Velo de Novia, lo que convierte en única en su tipo para Latinoamérica.', 'Se localiza en las divisiones territoriales de los municipios de Tzimol y Socoltenango, a 30 kilómetros de la ciudad de Comitán por la carretera Tuxtla-Comitán vía la Angostura.', NULL, NULL, 1, 'socio', '2021-05-05 16:52:59', '2021-05-05 16:52:59');
INSERT INTO `ecoturism_centers` VALUES (5, 'Cooperativa Cascada el Aguacero', 'cooperativa-cascada-el-aguacero', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654798/socios/CENTRO%20ECOTURISTICO%20CASCADA%20EL%20AGUACERO-20210403T064521Z-001/CENTRO%20ECOTURISTICO%20CASCADA%20EL%20AGUACERO/RioLaVenta7_yduktv.jpg', 'La preciosa cascada El Aguacero está formada por un río subterráneo y se encuentra dentro del impresionante Cañón de la Venta, donde corre el río del mismo nombre.', 'La preciosa cascada El Aguacero está formada por un río subterráneo y se encuentra dentro del impresionante Cañón de la Venta, donde corre el río del mismo nombre. Para la visita de este sitio natural, ¡se bajan y se suben 826 gradas! Un esfuerzo que recompensa el descubrimiento progresivo del entorno: paisajes, cuevas, vegetación... Es una experiencia inimaginable estar en este lugar en contacto con la naturaleza, caminar y nadar en sus pozas de aguas míticas, observando los fósiles que son grandes rocas sobre el lecho del río.', 'Se ubica en la región I centro, se llega por la carretera federal número 190, que se va a la Ciudad de México a 45 kilómetros de la ciudad de Tuxtla Gutiérrez y a 16 kilómetros de la ciudad de Ocozocoautla se encuentra el desvío de 3 kilómetros de terracería que conduce a la cascada (40 minutos de recorrido).', NULL, NULL, 1, 'socio', '2021-05-05 16:54:26', '2021-05-05 16:54:26');
INSERT INTO `ecoturism_centers` VALUES (6, 'Comunidad Lacanjá Chansayab, Ocosingo Chiapas', 'comunidad-lacanja-chansayab-ocosingo-chiapas', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654803/socios/RIO%20LACANJA-20210403T064638Z-001/RIO%20LACANJA/rafting10_loxrsr.jpg', 'En los márgenes de la Reserva de la Biosfera Montes Azules, se ubica uno de los sitios naturales habitado por los descendientes mayas.', 'En los márgenes de la Reserva de la Biosfera Montes Azules, se ubica uno de los sitios naturales habitado por los descendientes mayas. En la Selva Lacandona es posible a convivir con miembros del grupo lacandón y ver cómo conservan sus raíces sociales y culturales después de siglos de evolución social y humana.\r\nLacanjá Chansayab, es una comunidad lacandona que fundamenta su subsistencia a base de los recursos naturales que provee la biodiversidad de Montes Azules y al legado cultural maya manifestada en el monumento Natural de Bonampak.', 'Gracias a su ubicación, éste es un buen sitio que sirve de base para visitar los sitios arqueológicos de Bonampak y Lacanjá; además, estamos a 40 minutos de Frontera Corozal, poblado de donde parten las lanchas que navegan el río Usumacinta para visitar el sitio arqueológico de Yaxchilán.', NULL, NULL, 1, 'socio', '2021-05-05 16:58:11', '2021-05-05 16:58:11');
INSERT INTO `ecoturism_centers` VALUES (7, 'Campamento Chanaj - Margarito Chan Cayum', 'campamento-chanaj-margarito-chan-cayum', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654789/socios/CAMPAMENTO%20CHANAJ-20210403T054415Z-001/CAMPAMENTO%20CHANAJ/CAMINATA_EN_LA_SELVA_wl8ydd.jpg', 'Muy cerca de la zona arqueológica de Bonampak en la Selva Lacandona, se encuentra el campamento Chanaj de Margarito Chan Kayum.', 'Muy cerca de la zona arqueológica de Bonampak en la Selva Lacandona, se encuentra el campamento Chanaj de Margarito Chan Kayum. El campamento inicia operaciones en el año de 1994 con pequeñas palapas con hamaca para dormir, decoradas con artesanías de la región y pequeñas cabañas rústicas. Hoy en día cuenta con servicio de hospedaje en cabañas privadas y compartidas, área de camping y comedor. Para los amantes de la aventura, ofrecen caminatas guiadas para explorar la selva y servicio de transporte a las zonas arqueológicas de Bonampak, Yaxchilan y Plan de Ayutla Zak Tz´i.', 'Se ubica en la región VI selva, Lacanjá Chansayab se localiza en el corazón de la selva lacandona a 147 km. De la ciudad de Palenque por la carretera fronteriza a escasos 8 kms de la zona arqueológica de Bonampak.', NULL, NULL, 1, 'socio', '2021-05-05 17:00:04', '2021-05-05 17:00:04');
INSERT INTO `ecoturism_centers` VALUES (8, 'Campamento Cueva Tejón- Deysi Chanbor', 'campamento-cueva-tejon-deysi-chanbor', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654790/socios/CAMPAMENTO%20CUEVA%20DEL%20TEJON-20210403T054831Z-001/CAMPAMENTO%20CUEVA%20DEL%20TEJON/SELVA_LACANDONA_CASCADA_MOCTUNIHA_wyostu.jpg', 'En el corazón de la Reserva de la Biosfera de los Montes Azules, rodeados de naturaleza viva, el campamento Cueva Tejón cuenta con servicio de hospedaje en cabañas privadas con baño, área de camping y comedor.', 'En el corazón de la Reserva de la Biosfera de los Montes Azules, rodeados de naturaleza viva, el campamento Cueva Tejón cuenta con servicio de hospedaje en cabañas privadas con baño, área de camping y comedor.  Ofrece venta de artesanías en madera y en semillas silvestres. Si deseas aprender a elaborar estas artesanías, participa en el taller impartida por mujeres lacandonas. Descubre las bellezas de la selva lacandona en la caminata guiada en compañía de un guía local. \r\nLa comunidad lacandona quien vive en estos campamentos recibe el viajero para compartir con él o ella la magnificencia de la Selva Lacandona y su conocimiento profundo de este extraordinario ecosistema. La ubicación del campamento Cueva Tejón permite además visitar las zonas arqueológicas de Bonampak, Yaxchilan y Plan de Ayutla Zak Tz´i.', 'Se ubica en la región VI selva, Lacanjá Chansayab se localiza en el corazón de la selva lacandona a 147 km. De la ciudad de Palenque por la carretera fronteriza a escasos 8 kms de la zona arqueológica de Bonampak.', NULL, NULL, 1, 'socio', '2021-05-05 17:02:51', '2021-05-05 17:02:51');
INSERT INTO `ecoturism_centers` VALUES (9, 'Campamento Ya\'ajche - Martin Chankin Yuk', 'campamento-yaajche-martin-chankin-yuk', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654795/socios/CAMPAMENTO%20YA%20AJCHE-20210403T064358Z-001/CAMPAMENTO%20YA%20AJCHE/YAXCHILAN_nomlhg.jpg', 'Campamento ubicado en un entorno natural a la orilla de un pequeño río en la Selva Lacandona. Ya\'ajche se encuentra localizada en la comunidad lacandona de Lacanja Chansayab a dos horas y media de la ciudad de Palenque.', 'Campamento ubicado en un entorno natural a la orilla de un pequeño río en la Selva Lacandona. Ya\'ajche se encuentra localizada en la comunidad lacandona de Lacanja Chansayab a dos horas y media de la ciudad de Palenque. El Campamento ofrece servicio de hospedaje en cabañas rústicas o tradicionales, cabañas privadas con baño, área de acampar y comedor. Propone al visitante caminatas guiadas en la selva para descubrir la flora y fauna local. Su ubicación permite además visitar las zonas arqueológicas de Bonampak, Yaxchilan y Plan de Ayutla Zak Tz´i.', 'Se ubica en la región VI selva, Lacanjá Chansayab se localiza en el corazón de la selva lacandona a 147 km. De la ciudad de Palenque por la carretera fronteriza a escasos 8 kms de la zona arqueológica de Bonampak.', NULL, NULL, 1, 'socio', '2021-05-05 17:05:34', '2021-05-05 17:05:34');
INSERT INTO `ecoturism_centers` VALUES (10, 'Campamento Yatoch Barum – Vicente Kin Paniagua', 'campamento-yatoch-barum-vicente-kin-paniagua', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654797/socios/CAMPAMENTO%20YATOCH%20BARUM-20210403T064453Z-001/CAMPAMENTO%20YATOCH%20BARUM/ZA_LACANJA_karssf.jpg', 'El campamento Yatoch Barum está integrado por la familia del Sr. Vicente Kin Paniagua perteneciente a la etnia Maya Lacandón, originarios de la comunidad de Nahá ubicado al noreste de la Reserva de la Biosfera Montes Azules.', 'El campamento Yatoch Barum está integrado por la familia del Sr. Vicente Kin Paniagua perteneciente a la etnia Maya Lacandón, originarios de la comunidad de Nahá ubicado al noreste de la Reserva de la Biosfera Montes Azules. El campamento inicia sus operaciones a partir del año 1994 ofreciendo a los visitantes la oportunidad de disfrutar su estancia, de la biodiversidad de flora y fauna de la Selva Lacandona. Atravesado por un río, Yatoch Barum cuenta con  servicios de hospedaje en cabañas privadas con baño y habitaciones rústicas, área para acampar y para nadar, comedor y tienda de artesanías. En compañía de un miembro de la familia, se puede explorar la selva, caminando hacia las cascadas de Moctuniha y las ruinas de Lacanjá, observar la flora y fauna nativa, y por la noche disfrutar una tradicional fogata lacandona. Su ubicación permite además visitar las zonas arqueológicas de Bonampak, Yaxchilan y Plan de Ayutla Zak Tz´i.', 'Se ubica en la región VI selva, Lacanjá Chansayab se localiza en el corazón de la selva lacandona a 147 km. De la ciudad de Palenque por la carretera fronteriza a escasos 10 kms de la zona arqueológica de Bonampak.', NULL, NULL, 1, 'socio', '2021-05-05 17:07:12', '2021-05-05 17:07:12');
INSERT INTO `ecoturism_centers` VALUES (11, 'Campamento Top Che (Enrique Chan Kin Paniagua)', 'campamento-top-che-enrique-chan-kin-paniagua', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654794/socios/CAMPAMENTO%20TOP%20CHE-20210403T064347Z-001/CAMPAMENTO%20TOP%20CHE/RAFTING_EN_RIO_LACANJA111_b5va3l.jpg', 'En el corazón de la Selva Lacandona, a dos horas y media de Palenque, se encuentra este campamento familiar lacandón, un lugar rústico y auténtico, dónde podrás convivir con esta acogedora familia lacandona y olvidarse de lo cotidiano.', 'En el corazón de la Selva Lacandona, a dos horas y media de Palenque, se encuentra este campamento familiar lacandón, un lugar rústico y auténtico, dónde podrás convivir con esta acogedora familia lacandona y olvidarse de lo cotidiano. El campamento Top Che está dirigido por la familia del Sr. Enrique Chankin Paniagua. El campamento ofrece servicio de hospedaje en cabañas rústicas y privadas con baño, comedor y caminatas guiadas en la selva para descubrir el maravilloso entorno de la Reserva. Su ubicación permite además visitar las zonas arqueológicas de  Bonampak, Yaxchilan y Plan de Ayutla-Zak Tz´i.', 'Se ubica en la región VI selva, Lacanjá Chansayab se localiza en el corazón de la selva lacandona a 147 km. De la ciudad de Palenque por la carretera fronteriza a escasos 10 kms de la zona arqueológica de Bonampak.', NULL, NULL, 1, 'socio', '2021-05-05 17:08:40', '2021-05-05 17:08:40');
INSERT INTO `ecoturism_centers` VALUES (12, 'Campamento Río Lacanjá-Ricardo Chambor Kin', 'campamento-rio-lacanja-ricardo-chambor-kin', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654803/socios/RIO%20LACANJA-20210403T064638Z-001/RIO%20LACANJA/rafting10_loxrsr.jpg', 'Campamento lacandón ubicado en la Reserva de Montes Azules, a dos horas y media de Palenque. Río Lacanjá se encuentra en un entorno natural extraordinario. Ofrece servicio de hospedaje en cabañas rústicas a orilla del río y cabañas privadas rodeadas de una vegetación exuberante, comedor, internet satelital en recepción, y un sendero interpretativo que conduce a un manantial y a la milpa tradicional lacandona.', 'Campamento lacandón ubicado en la Reserva de Montes Azules, a dos horas y media de Palenque. Río Lacanjá se encuentra en un entorno natural extraordinario. Ofrece servicio de hospedaje en cabañas rústicas a orilla del río y cabañas privadas rodeadas de una vegetación exuberante, comedor, internet satelital en recepción, y un sendero interpretativo que conduce a un manantial y a la milpa tradicional lacandona.\r\n \r\nSi eres un viajero de espíritu aventurero, te recomendamos la caminata a través de la selva para visitar la cascada de Moctuniha, donde podrás nadar en las pozas que se forman en torno a ella; y si deseas un poco de adrenalina, el descenso en balsa (rafting) sobre el rio Lacanjá  es el medio más divertido para internarse en la espesura de la selva lacandona.\r\nSu ubicación permite además visitar las zonas arqueológicas de Bonampak y Yaxchilan y Plan de Ayutla Zak Tz´i.', 'Se ubica en la región VI selva, Lacanjá Chansayab se localiza en el corazón de la selva lacandona a 147 km. De la ciudad de Palenque por la carretera fronteriza a escasos 12 kms de la zona arqueológica de Bonampak.', NULL, NULL, 1, 'socio', '2021-05-05 17:10:02', '2021-05-05 17:10:02');
INSERT INTO `ecoturism_centers` VALUES (13, 'Campamentos lacandones', 'campamentos-lacandones', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654807/colaboradores/CAMPAMENTO%20LACANDONES-20210403T194300Z-001/CAMPAMENTO%20LACANDONES/AREAS_VERDES-FOGATA_LACANDONA_pafbmn.jpg', 'Certificado por la secretaría de medio ambiente con instalaciones congruentes con el entorno, Campamento Lacandones es el lugar ideal para disfrutar de la naturaleza y la tranquilidad.', 'Certificado por la secretaría de medio ambiente con instalaciones congruentes con el entorno, Campamento Lacandones es el lugar ideal para disfrutar de la naturaleza y la tranquilidad.\r\nAprende en compañía de esta comunidad descendiente directa de los mayas, fieles guardianes de sus culturas tradicionales y de los vestigios arqueológicos de la zona. Descubre la magia de la selva de Chiapas y admira los hermosos paisajes, las increíbles cascadas y las pozas naturales.', 'El campamento se encuentra ubicado en plena Selva Lacandona, en la población de Lacanjá Chansayab. A escasos kilómetros de las Ruinas Mayas de Bonampak\r\n\r\nEl Campamento Lacandones se encuentra a 35 km de la Ciudad Maya de Yaxchilán, a 2.30 horas en coche del Parque Nacional de Palenque y a 4.00 horas en coche del Aeropuerto Internacional de Villahermosa, Tabasco.', NULL, NULL, 1, 'colaborador', '2021-05-05 17:23:18', '2021-05-05 17:23:18');
INSERT INTO `ecoturism_centers` VALUES (14, 'Campamento Sak Nok', 'campamento-sak-nok', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654808/colaboradores/CAMPAMENTO%20SAK%20NOK-20210403T194312Z-001/CAMPAMENTO%20SAK%20NOK/CASCADA_MOCTUNIHA-CAMINATA_EN_LA_SELVA1_ukcjmf.jpg', 'Eco Hotel Sak Nok, casa de los hombres verdaderos, se encuentra ubicado en la comunidad de Lacanjá Chansayab, a 13 km de Bonampak.', 'Este eco-hotel ofrece una estancia inolvidable en sus cabañas rústicas. Todos los alojamientos disponen de terraza con vista a la montaña y baño privado. Este es un excelente punto de partida para aquellos que desean visitar el sitio arqueológico de Bonampak, la ciudad de los muros pintados, y que están a solo 13 km del hotel. Y de un recorrido a un sitio arqueológico inexplorado llamado Lacanjá.\r\nEste centro ofrece actividades de convivencia con la naturaleza, todo apegado a la conservación y preservación del entorno natural único.', 'Partiendo de la ciudad de Palenque primero deberá tomar la carretera federal fronteriza hasta el crucero Shupá y después conducir sobre la carretera Fronteriza del Sur que conduce a bonampak, se recorren 132 km hasta llegar al crucero San Javier y desde este punto, se transita 8 km hasta llegar a la comunidad Lacanjá Chansayab, Lugar donde está ubicado el Campamento.', NULL, NULL, 1, 'colaborador', '2021-05-05 17:26:08', '2021-05-05 17:26:08');
INSERT INTO `ecoturism_centers` VALUES (15, 'Cañón del jabalí', 'canon-del-jabali', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654812/colaboradores/CA%C3%91ON%20DEL%20JABALI-20210403T194328Z-001/CA%C3%91ON%20DEL%20JABALI/IMG_9083_edited_suh44h.jpg', 'Es un pequeño cañón de vegetación exuberante, donde el agua verde turquesa forma una impresionante cascada que se extiende río abajo.', 'Es un pequeño cañón de vegetación exuberante, donde el agua verde turquesa forma una impresionante cascada que se extiende río abajo.\r\n\r\nEl Centro Ecoturístico Cañón del Jabalí, se encuentra asentado sobre la rivera multicolor del río Santo Domingo, cuyo cauce y la vegetación circundante son los principales atractivos. Este maravilloso lugar es ideal para recibir pequeños grupos ya sea para aventura o bien sea para viajes de incentivo.', 'Ejido Jerusalén, municipio las Margaritas, Chiapas, México', NULL, NULL, 1, 'colaborador', '2021-05-05 17:28:14', '2021-05-05 17:28:14');
INSERT INTO `ecoturism_centers` VALUES (16, 'Centro Ecoturístico el chiflón', 'centro-ecoturistico-el-chiflon', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654809/colaboradores/CASCADAS%20EL%20CHIFLON-20210403T194339Z-001/CASCADAS%20EL%20CHIFLON/CASCADAS_EL_CHIFLON_wkfepo.jpg', 'Ubicado en el municipio de Tzimol, a solo 40 minutos de Comitán, Chiapas, se encuentra este balneario donde la comunidad indígena se ha encargado de desarrollarlo  para disfrutar en familia este parque ecoturístico, Aprovecha para zambullirse en las aguas cristalinas de las pozas naturales que se forman.', 'Ubicado en el municipio de Tzimol, a solo 40 minutos de Comitán, Chiapas, se encuentra este balneario donde la comunidad indígena se ha encargado de desarrollarlo  para disfrutar en familia este parque ecoturístico, Aprovecha para zambullirse en las aguas cristalinas de las pozas naturales que se forman.\r\nDisfruta en familia, de las diferentes actividades que ofrece el sitio: juegos infantiles, tienda de artesanías, museo de interpretación ambiental, sala  audiovisual, observación de iguanas en su habitat, palapas y asadores ideales para un día de campo, zambullirte en las pozas y admirar la grandeza de las cascadas.\r\nEn El Chiflón, también puedes disfrutar de actividades más extremas como  tirolesas, una de 140 m y otra  de 70m.', 'Ubicado en el municipio de Tzimol, a solo 40 minutos de Comitán.', NULL, NULL, 1, 'colaborador', '2021-05-05 17:30:16', '2021-05-05 17:30:16');
INSERT INTO `ecoturism_centers` VALUES (17, 'Centro ecoturístico causas verdes las nubes', 'centro-ecoturistico-causas-verdes-las-nubes', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654813/colaboradores/CENTRO%20ECOTURISTICO%20CAUSAS%20VERDES%20LAS%20NUBES-20210403T194355Z-001/CENTRO%20ECOTURISTICO%20CAUSAS%20VERDES%20LAS%20NUBES/IMG-20200311-WA0012_am81mi.jpg', 'En el año 2002 un grupo de campesinos nos organizamos para constituir una sociedad cooperativa, así nació Causas Verdes Las Nubes. Nuestra filosofía de conservar nuestros recursos naturales nos ha permitido colocarnos en el gusto de los viajeros de nuestro país y de todo el mundo.', 'En el año 2002 un grupo de campesinos nos organizamos para constituir una sociedad cooperativa, así nació Causas Verdes Las Nubes. Nuestra filosofía de conservar nuestros recursos naturales nos ha permitido colocarnos en el gusto de los viajeros de nuestro país y de todo el mundo.\r\n\r\nAmanece con los sonidos de la naturaleza en nuestro hermoso Centro Ecoturístico enclavado en los linderos entre Selva Lacandona y la Reserva de la Biósfera de Montes Azules de Chiapas. Aquí los ruidos de los autos son reemplazados por el canto de las aves, y en vez del tráfico se escucha el agua de la cascada Las Nubes. Aléjate del bullicio de la ciudad, deja atrás las prisas y el estrés y disfruta de un paraíso salvaje rebosante de vida.', 'Causas Verdes Las Nubes, el centro ecoturístico más exitoso de Chiapas en los últimos años, es una maravilla natural enclavada en la zona de La Selva Lacandona, en el municipio de Maravilla Tenejapa. A una distancia de 120 kilómetros (dos horas de camino) de la ciudad de Comitán, Chiapas, se encuentra Causas Verdes Las Nubes, un ejido de 276 habitantes indígenas tzotziles y tzeltales que ofrece una alternativa de ecoturismo muy interesante que la ha convertido en una de las más exitosas del estado en los últimos años.', NULL, NULL, 1, 'colaborador', '2021-05-05 17:34:03', '2021-05-05 17:34:03');
INSERT INTO `ecoturism_centers` VALUES (18, 'Centro ecoturístico nueva alianza', 'centro-ecoturistico-nueva-alianza', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654816/colaboradores/CENTRO%20ECOTURISTICO%20NUEVA%20ALIANZA-20210403T194410Z-001/CENTRO%20ECOTURISTICO%20NUEVA%20ALIANZA/YAXCHILAN_11_s9hpuh.jpg', 'Nuestra comunidad indigena “Frontera Corozal” es una comunidad de la etnia Chól. Asentada en los márgenes del Río Usumacinta que sirve de frontera entre México y Guatemala además de ser el enlace fluvial con la zona arqueológica de Yaxchilán y la zona arqueológica de Tikal (Guatemala).', 'Nuestra comunidad indigena “Frontera Corozal” es una comunidad de la etnia Chól. Asentada en los márgenes del Río Usumacinta que sirve de frontera entre México y Guatemala además de ser el enlace fluvial con la zona arqueológica de Yaxchilán y la zona arqueológica de Tikal (Guatemala). Los choles son los Winik, del vocablo maya que significa \"hombre, varón\"; son \"los milperos\", los hombres creados del maíz que viven y explican su existencia en torno al maíz, alimento sagrado otorgado por los dioses, principio y fin de la vida, y eje central de su concepción del mundo. Los recursos naturales de la zona, la historia y las tradiciones de sus antepasados.\r\n\r\nHoy en dia, este grupo se encarga de proveer servicios turísticos a los visitantes y también proteger y conservar los recursos naturales de la zona, la historia y las tradiciones de sus antepasados', NULL, NULL, NULL, 1, 'colaborador', '2021-05-05 17:37:43', '2021-05-05 17:37:43');
INSERT INTO `ecoturism_centers` VALUES (19, 'Ciudad de las rocas', 'ciudad-de-las-rocas', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654817/colaboradores/CIUDAD%20DE%20LAS%20ROCAS-20210403T194424Z-001/CIUDAD%20DE%20LAS%20ROCAS/TIROLESA_CIUDAD_DE_LAS_ROCAS_2_hziw4v.jpg', 'Cooperativa integrada por ejidatarios e hijo de la comunidad Las Nubes., que en el año 2012 se organizaron para formar el Centro Ecoturístico Ciudad de las Rocas. Para 2013 es constituida por un grupo de 20 mujeres y hombres indígenas, quienes buscan generar empleos y mayores ingresos económicos a sus familias, cuidando y protegiendo la flora y fauna del lugar.', 'Cooperativa integrada por ejidatarios e hijo de la comunidad Las Nubes., que en el año 2012 se organizaron para formar el Centro Ecoturístico Ciudad de las Rocas. Para 2013 es constituida por un grupo de 20 mujeres y hombres indígenas, quienes buscan generar empleos y mayores ingresos económicos a sus familias, cuidando y protegiendo la flora y fauna del lugar.\r\n\r\nOfrecen actividades como senderismo, canoping, tirolesa, descenso en cueva, rappel, caminata por laberintos de rocas, rafting  y ciclismo. Servicios de restaurante con comidas caceras y servicio de hospedaje y área de camping. Además de disfrutar de las aguas del río Santo Domingo, mientras nadas en ella.', NULL, NULL, NULL, 1, 'colaborador', '2021-05-05 17:38:50', '2021-05-05 17:38:50');
INSERT INTO `ecoturism_centers` VALUES (20, 'Lagos de colon', 'lagos-de-colon', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654818/colaboradores/LAGOS%20DE%20COLON-20210403T194434Z-001/LAGOS%20DE%20COLON/_MG_6178_nslpcd.jpg', 'Sistema lagunario ubicado en el ejido Cristóbal Colón, muy cercano a la zona arqueológica el Lagartero; las lagunas son de aguas cristalinas y de baja profundidad interconectadas entre sí por canales en una superficie de 350 hectáreas donde se encuentran 44 hermosos lagos que permiten apreciar las diversas tonalidades en azul ultramar.', 'Sistema lagunario ubicado en el ejido Cristóbal Colón, muy cercano a la zona arqueológica el Lagartero; las lagunas son de aguas cristalinas y de baja profundidad interconectadas entre sí por canales en una superficie de 350 hectáreas donde se encuentran 44 hermosos lagos que permiten apreciar las diversas tonalidades en azul ultramar.\r\n\r\nLos Lagos de Colón están en un hermoso paraje creado por un río procedente de Guatemala que al entrar a Chiapas reduce su velocidad, se separa en múltiples brazos y forma una serie de encantadoras pozas cristalinas con tonos verdiazules. \r\n\r\nLos Lagos de Colón son un balneario natural y un excelente lugar para los amantes del buceo y snorkel. Ofrece servicio de hospedaje, restaurante y comedores comunitarios, renta de cayak y guías locales para visitar el sitio.', 'Se localiza en el municipio de La Trinitaria, en la Región Fronteriza del estado, a 73km de Comitán de Domínguez.', NULL, NULL, 1, 'colaborador', '2021-05-05 17:40:29', '2021-05-05 17:40:29');
INSERT INTO `ecoturism_centers` VALUES (21, 'Lodge & Eco-Hotel Naha', 'lodge-eco-hotel-naha', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654818/colaboradores/NAHA%20JUNGLE%20LODGE-20210403T194454Z-001/NAHA%20JUNGLE%20LODGE/NAHA_JUNGLE_LODGE1_p58ghx.jpg', 'Nahá, la casa del agua, nos invita a aventurarnos en la exuberancia de la naturaleza, a conectarnos con la sinfonía de las aves, a descubrir las curiosas especies de mamíferos y reptiles que habitan el bosque, a gozar nuestra propia esencia y a ser parte de la magia de una comunidad ancestral que comparte sus saberes con los viajeros del mundo.', 'Nahá, la casa del agua, nos invita a aventurarnos en la exuberancia de la naturaleza, a conectarnos con la sinfonía de las aves, a descubrir las curiosas especies de mamíferos y reptiles que habitan el bosque, a gozar nuestra propia esencia y a ser parte de la magia de una comunidad ancestral que comparte sus saberes con los viajeros del mundo.\r\n\r\nSomos un grupo de personas de la comunidad lacandona de Nahá, comprometidas con cuidar nuestra selva y participar en el desarrollo sostenible de las  21 familias que vivimos en armonía con el entorno. \r\nGracias al trabajo continuo y los recursos que generamos atendiendo a nuestros visitantes, hemos logrado instalar sistemas de tratamiento de aguas residuales y de captación de lluvia, utilizamos energía solar y buscamos seguir contribuyendo a favor de la naturaleza.\r\nNaturaleza, amistad, hospitalidad y armonía son palabras que cobran vida en Nahá Jungle Lodge y crean simbiosis entre el entorno, la comunidad y los visitantes. \r\nNuestro Jungle Lodge cuenta con certificación de la norma NMX-AA-133-SCFI-2006, con lo que garantizamos que nuestros procesos nos conducen de forma efectiva para lograr la sustentabilidad de nuestros recursos.', 'Nahá Jungle Lodge es un refugio situado en la profundidad de la selva lacandona, rodeado de fértiles lagunas que inspiran a la comunidad a proteger su espíritu libre.', NULL, NULL, 1, 'colaborador', '2021-05-05 17:42:46', '2021-05-05 17:42:46');
INSERT INTO `ecoturism_centers` VALUES (22, 'Centro ecoturístico Eco-Tziscao', 'centro-ecoturistico-eco-tziscao', 'https://res.cloudinary.com/sendasur-com/image/upload/v1617654820/colaboradores/TZISCAO-20210403T194504Z-001/TZISCAO/HABITACI%C3%93N_PRIVADA1_arfoml.jpg', 'Recorre las más de 30 lagunas de color azul turquesa, entre cerros y cañadas de este sitio que forma parte del Parque Nacional Lagunas de Montebello en Chiapas, donde junto con la comunidad Mam puedes hacer caminatas conociendo los senderos rodeados de encinos, pinos, robles, así como, orquídeas y bromelias espectaculares, que son hogar de fauna como quetzales, tucancillos, oso hormiguero, ardillos, loros y muchos más.', 'Recorre las más de 30 lagunas de color azul turquesa, entre cerros y cañadas de este sitio que forma parte del Parque Nacional Lagunas de Montebello en Chiapas, donde junto con la comunidad Mam puedes hacer caminatas conociendo los senderos rodeados de encinos, pinos, robles, así como, orquídeas y bromelias espectaculares, que son hogar de fauna como quetzales, tucancillos, oso hormiguero, ardillos, loros y muchos más. Explora las lagunas en balsa rústica, una actividad típica de aquí, o toma un kayak en la laguna Pojoj para visitar la isla del orquideario conservado por la comunidad. El museo comunitario, las artesanías, las rutas para bicicleta de montaña, las competencias deportivas eventuales y la comodidad de sus instalaciones y servicios son otro gran motivo para visitarlo.', NULL, NULL, NULL, 1, 'colaborador', '2021-05-05 17:46:30', '2021-05-05 17:46:30');

-- ----------------------------
-- Table structure for failed_jobs
-- ----------------------------
DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp(0) NOT NULL DEFAULT current_timestamp(0),
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `failed_jobs_uuid_unique`(`uuid`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of failed_jobs
-- ----------------------------

-- ----------------------------
-- Table structure for migrations
-- ----------------------------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of migrations
-- ----------------------------
INSERT INTO `migrations` VALUES (1, '2014_10_12_000000_create_users_table', 1);
INSERT INTO `migrations` VALUES (2, '2014_10_12_100000_create_password_resets_table', 1);
INSERT INTO `migrations` VALUES (3, '2019_08_19_000000_create_failed_jobs_table', 1);
INSERT INTO `migrations` VALUES (4, '2021_04_30_063811_create_ecoturism_centers_table', 1);

-- ----------------------------
-- Table structure for password_resets
-- ----------------------------
DROP TABLE IF EXISTS `password_resets`;
CREATE TABLE `password_resets`  (
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  INDEX `password_resets_email_index`(`email`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of password_resets
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp(0) NULL DEFAULT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `created_at` timestamp(0) NULL DEFAULT NULL,
  `updated_at` timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `users_email_unique`(`email`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------

SET FOREIGN_KEY_CHECKS = 1;
